# Generated by Django 3.1.1 on 2020-10-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('content', models.TextField(verbose_name='Контент')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('posts.post',),
        ),
    ]
