# Generated by Django 3.1.1 on 2020-10-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comments', '0002_auto_20201017_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='posts.post'),
        ),
    ]
