# Generated by Django 3.1.1 on 2020-11-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comments', '0006_auto_20201025_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodeclosure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nodeclosure',
            name='child',
        ),
        migrations.RemoveField(
            model_name='nodeclosure',
            name='parent',
        ),
        migrations.AlterField(
            model_name='commenthierarchy',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='comments.postcomment'),
        ),
        migrations.AlterField(
            model_name='commenthierarchy',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='comments.postcomment'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='NodeClosure',
        ),
    ]
